// v0.6 Task B: A2 playback through Sawblade's real load path (NamBlock), against the pinned trainer's own forward pass.
// Fixtures: tests/fixtures/a2 (synthetic, generated by generate.py with neural-amp-modeler 0.13.0).
#include <algorithm>
#include <catch2/catch_test_macros.hpp>
#include <cmath>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <string>
#include <typeinfo>
#include <vector>

#include "NAM/get_dsp.h"
#include "NAM/wavenet/a2_fast.h"
#include "alloc_guard.h"
#include "json.hpp"
#include "sawblade/nam_block.h"
#include "sawblade/wav_io.h"
#include "test_util.h"

using namespace sawblade;
using namespace sawblade::test;
namespace fs = std::filesystem;

namespace {

constexpr double kFs = 48000.0;

fs::path fx(const std::string& name) { return fs::path(SAWBLADE_FIXTURES_DIR) / "a2" / name; }

std::vector<float> readMono(const std::string& name) {
  const AudioFile f = readWav(fx(name));
  REQUIRE(f.channels == 1);
  REQUIRE(f.sampleRate == kFs);
  return f.interleaved;
}

std::unique_ptr<NamBlock> makeBlock(const std::string& nam, int maxBlock = 512) {
  auto b = NamBlock::load(fx(nam), NamBlockConfig{});  // gains 0 dB, no loudness normalisation: raw model output
  b->prepare({kFs, maxBlock});
  return b;
}

std::vector<float> render(NamBlock& b, std::vector<float> x, int block) {
  std::size_t pos = 0;
  while (pos < x.size()) {
    const int n = static_cast<int>(std::min<std::size_t>(static_cast<std::size_t>(block), x.size() - pos));
    b.process(x.data() + pos, n);
    pos += static_cast<std::size_t>(n);
  }
  return x;
}

double maxAbsDiff(const std::vector<float>& a, const std::vector<float>& b, std::size_t from = 0) {
  REQUIRE(a.size() == b.size());
  double m = 0.0;
  for (std::size_t i = from; i < a.size(); ++i) m = std::max(m, std::fabs(static_cast<double>(a[i]) - b[i]));
  return m;
}

nlohmann::json readJson(const fs::path& p) {
  std::ifstream in(p);
  REQUIRE(in.good());
  return nlohmann::json::parse(in);
}

struct Case {
  const char* nam;
  const char* ref;
};
const Case kCases[] = {{"a2_full.nam", "ref_a2_full.wav"},
                       {"a2_lite.nam", "ref_a2_lite.wav"},
                       {"a2_container.nam", "ref_a2_full.wav"},  // an unsized container plays its last (Full) submodel
                       {"a1_standard.nam", "ref_a1_standard.wav"}};

// Null tolerance vs the trainer's float32 PyTorch forward pass. The reference peaks at 0.035 to 0.059 (-24 to -29 dBFS);
// the player is float32 with a different summation order (and, for A2, hand-written kernels), so the expected difference is
// float rounding accumulated through 23 layers: ~1e-7 relative to the signal. 1e-5 absolute is ~250x above what is
// measured here (<= 3.7e-8 on gcc/x86, release) and ~60 dB below the quietest reference peak, so a wrong weight, kernel, dilation or activation (which
// shows up at 1e-2 to 1e-1) cannot hide, while a different compiler / CPU / vector width cannot flake it.
constexpr double kNullTol = 1e-5;
// Different block sizes only change the order in which the same per-sample recurrence is evaluated; allowed 1e-6 so the
// test also holds on a compiler that vectorises the block loops differently (measured: bit-identical on gcc/x86).
constexpr double kBlockTol = 1e-6;

}  // namespace

TEST_CASE("A2 fixtures: null test against the trainer's forward pass", "[a2][nam]") {
  const auto x = readMono("input.wav");
  for (const auto& c : kCases) {
    DYNAMIC_SECTION(c.nam) {
      const auto ref = readMono(c.ref);
      REQUIRE(ref.size() == x.size());
      auto b = makeBlock(c.nam);
      const auto y = render(*b, x, 64);
      const double d = maxAbsDiff(y, ref);
      INFO("max |player - trainer| = " << d);
      std::printf("[a2 null] %-18s max|diff| %.3e over %zu samples\n", c.nam, d, x.size());
      REQUIRE(d <= kNullTol);
      // The output must really be the model's, not silence or the dry input.
      REQUIRE(rms(y.data(), y.size()) > 0.01);
    }
  }
}

TEST_CASE("A2 fixtures: start-up (prewarm) agrees with the trainer's zero history from sample 0", "[a2][nam]") {
  // The trainer's reference starts from zero history; NamBlock::prepare() = ResetAndPrewarm (prewarm input is zeros).
  // The fixtures' input starts with noise at sample 0 (5 ms fade-in), so a start-up mismatch would show in the first
  // receptive field. Check that region on its own, with the same tolerance.
  const auto x = readMono("input.wav");
  struct R { const char* nam; const char* ref; std::size_t rf; };
  for (const R r : {R{"a2_full.nam", "ref_a2_full.wav", 6347}, R{"a2_lite.nam", "ref_a2_lite.wav", 6347},
                    R{"a2_container.nam", "ref_a2_full.wav", 6347}, R{"a1_standard.nam", "ref_a1_standard.wav", 4093}}) {
    DYNAMIC_SECTION(r.nam) {
      const auto ref = readMono(r.ref);
      auto b = makeBlock(r.nam);
      const auto y = render(*b, x, 512);
      std::vector<float> y0(y.begin(), y.begin() + static_cast<std::ptrdiff_t>(r.rf));
      std::vector<float> r0(ref.begin(), ref.begin() + static_cast<std::ptrdiff_t>(r.rf));
      REQUIRE(maxAbsDiff(y0, r0) <= kNullTol);
      REQUIRE(rms(r0.data(), r0.size()) > 1e-4);  // the region is not trivially quiet
    }
  }
}

TEST_CASE("A2 fixtures: reported latency and prewarm", "[a2][nam]") {
  for (const auto& c : kCases) {
    DYNAMIC_SECTION(c.nam) {
      auto b = makeBlock(c.nam);
      // No latency API in the core and the trainer aligns the capture: reported latency is 0 for A1 and A2 alike.
      REQUIRE(b->latencySamples() == 0);
      REQUIRE(b->expectedSampleRate() == kFs);
    }
  }
  // The receptive field (= prewarm length, the core's GetPrewarmSamples) is the manifest's number: 6347 for both A2
  // sizes and the container, 4093 for A1 standard. It is not latency, but it is the cost of prepare()/reset().
  const auto mf = readJson(fx("manifest.json"));
  for (const auto& [name, rf] : {std::pair<const char*, int>{"a2_full", 6347}, {"a2_lite", 6347}, {"a2_container", 6347},
                                  {"a1_standard", 4093}}) {
    REQUIRE(mf["models"][name]["receptiveFieldSamples"].get<int>() == rf);
    REQUIRE(mf["models"][name]["algorithmicLatencySamples"].get<int>() == 0);
    auto dsp = nam::get_dsp(fx(std::string(name) + ".nam"));
    REQUIRE(dsp != nullptr);
    INFO(name);
    REQUIRE(dsp->GetPrewarmSamples() == rf);
  }
}

TEST_CASE("A2 container: plays the Full submodel and carries Sawblade metadata", "[a2][nam]") {
  const auto x = readMono("input.wav");
  auto full = makeBlock("a2_full.nam");
  auto cont = makeBlock("a2_container.nam");
  // Same network, same weights, same fast path: the container must equal the standalone Full file (and not Lite).
  const auto yf = render(*full, x, 64);
  const auto yc = render(*cont, x, 64);
  REQUIRE(maxAbsDiff(yf, yc) <= kBlockTol);
  auto lite = makeBlock("a2_lite.nam");
  REQUIRE(maxAbsDiff(render(*lite, x, 64), yc) > 1e-3);
  // Top-level metadata of the container reaches Sawblade (name, gear type, modeled_by).
  REQUIRE(cont->metadata().gearType == "amp");
  REQUIRE_FALSE(cont->metadata().name.empty());
  REQUIRE_FALSE(cont->metadata().modeledBy.empty());
  REQUIRE(cont->loudnessDb().has_value());
}

TEST_CASE("A2 fixtures: process() performs no allocations", "[a2][nam][alloc]") {
  for (const auto& c : kCases) {
    DYNAMIC_SECTION(c.nam) {
      auto b = makeBlock(c.nam, 512);
      std::vector<float> buf = noise(512, 8, 0.3f);
      const int sizes[] = {512, 1, 7, 64, 333, 128, 2, 500, 17, 256, 512, 1, 100, 64, 64, 64};
      long allocs = -1;
      {
        AllocGuard g;
        for (const int n : sizes) b->process(buf.data(), n);
        allocs = g.count();
      }
      REQUIRE(allocs == 0);
    }
  }
}

TEST_CASE("A2 fixtures: block-size independence", "[a2][nam]") {
  const auto x = readMono("input.wav");
  for (const auto& c : kCases) {
    DYNAMIC_SECTION(c.nam) {
      auto base = makeBlock(c.nam, 512);
      const auto y512 = render(*base, x, 512);
      for (const int bs : {1, 37, 64}) {
        INFO("block " << bs);
        auto b = makeBlock(c.nam, 512);
        const double d = maxAbsDiff(render(*b, x, bs), y512);
        std::printf("[a2 blocks] %-18s block %3d vs 512: max|diff| %.3e\n", c.nam, bs, d);
        REQUIRE(d <= kBlockTol);
      }
      // prepare() with a different maxBlockSize must not change the result either.
      auto b64 = makeBlock(c.nam, 64);
      REQUIRE(maxAbsDiff(render(*b64, x, 64), y512) <= kBlockTol);
    }
  }
}

TEST_CASE("A2 fixtures: determinism (fresh blocks, reset, repeat)", "[a2][nam]") {
  const auto x = readMono("input.wav");
  for (const auto& c : kCases) {
    DYNAMIC_SECTION(c.nam) {
      auto a = makeBlock(c.nam);
      auto b = makeBlock(c.nam);
      const auto ya = render(*a, x, 64);
      REQUIRE(ya == render(*b, x, 64));  // two instances: bit-identical
      a->reset();
      REQUIRE(ya == render(*a, x, 64));  // reset() restores the start-up state exactly
      auto m = NamModel::load(fx(c.nam));
      auto d = NamBlock::load(*m, NamBlockConfig{});
      d->prepare({kFs, 512});
      REQUIRE(ya == render(*d, x, 64));  // CaptureCache's load path (NamModel) is bit-identical to load(path)
    }
  }
}

TEST_CASE("A2 Full and Lite take the NAM_ENABLE_A2_FAST path", "[a2][nam]") {
  // The core exposes the shape detector in a public header (NAM/wavenet/a2_fast.h, only compiled with
  // NAM_ENABLE_A2_FAST: this file would not build without the macro). wavenet::create_config calls it on every non-slimmable
  // WaveNet config and, on a match, builds A2FastModel<channels> instead of the generic WaveNet. We check both halves:
  // the detector on the file's config, and the dynamic type that get_dsp() really returns.
  auto typeOf = [](const fs::path& p) {
    auto dsp = nam::get_dsp(p);
    REQUIRE(dsp != nullptr);
    const nam::DSP& d = *dsp;  // (typeid(*dsp) on a smart pointer trips clang's -Wpotentially-evaluated-expression)
    return std::string(typeid(d).name());
  };
  for (const auto& [file, ch] : {std::pair<const char*, int>{"a2_full.nam", 8}, {"a2_lite.nam", 3}}) {
    DYNAMIC_SECTION(file) {
      const auto j = readJson(fx(file));
      int channels = 0;
      REQUIRE(nam::wavenet::a2_fast::is_a2_shape(j["config"], &channels));
      REQUIRE(channels == ch);
      REQUIRE(typeOf(fx(file)).find("A2FastModel") != std::string::npos);
    }
  }
  // A1 standard is not A2-shaped and stays on the generic WaveNet.
  {
    const auto j = readJson(fx("a1_standard.nam"));
    int channels = 0;
    REQUIRE_FALSE(nam::wavenet::a2_fast::is_a2_shape(j["config"], &channels));
    REQUIRE(typeOf(fx("a1_standard.nam")).find("A2FastModel") == std::string::npos);
  }
  // The container's submodels are built through get_dsp, so each A2 submodel gets the fast path too.
  {
    const auto j = readJson(fx("a2_container.nam"));
    REQUIRE(j["architecture"] == "SlimmableContainer");
    int seen = 0;
    for (const auto& sm : j["config"]["submodels"]) {
      int channels = 0;
      REQUIRE(nam::wavenet::a2_fast::is_a2_shape(sm["model"]["config"], &channels));
      ++seen;
      // The core keeps the active submodel private, so build each submodel the way the container does (get_dsp on its
      // nested model) and check the dynamic type: Full (8 ch, the one the container plays) and Lite both take the fast path.
      auto sub = nam::get_dsp(sm["model"]);
      REQUIRE(sub != nullptr);
      const nam::DSP& sd = *sub;
      REQUIRE(std::string(typeid(sd).name()).find("A2FastModel") != std::string::npos);
    }
    REQUIRE(seen == 2);
  }
  // Negative control: one knob off the A2 shape (one layer's LeakyReLU slope) falls back to the generic WaveNet,
  // which proves the type check above can tell the two paths apart.
  {
    auto j = readJson(fx("a2_full.nam"));
    j["config"]["layers"][0]["activation"][0]["negative_slope"] = 0.02;
    int channels = 0;
    REQUIRE_FALSE(nam::wavenet::a2_fast::is_a2_shape(j["config"], &channels));
    auto dsp = nam::get_dsp(j);
    REQUIRE(dsp != nullptr);
    const nam::DSP& d = *dsp;
    REQUIRE(std::string(typeid(d).name()).find("A2FastModel") == std::string::npos);
  }
}
