// Export notes (v0.4 Task E): the C++ port of v0.4M's notes.py must reproduce the Python output. The fixtures in
// tests/fixtures/export_notes/ were generated by running that Python (generate.py there has the command).
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <random>
#include <string>

#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <nlohmann/json.hpp>

#include "ExportNotes.h"
#include "ExportSettings.h"
#include "JobRunner.h"
#include "sawblade/preset.h"

using nlohmann::json;
using namespace sawblade;
using namespace sawblade::plugin;
namespace fs = std::filesystem;

namespace {

const fs::path kDir = fs::path(SAWBLADE_EXPORT_NOTES_DIR);

std::string readText(const fs::path& p) {
  std::ifstream f(p, std::ios::binary);
  REQUIRE(f.good());
  return std::string((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
}
json readJson(const fs::path& p) { return json::parse(readText(p)); }

// Numbers within 1e-9 (an int and a float of the same value are equal), strings and everything else exact.
bool sameJson(const json& a, const json& b, const std::string& where, std::string* why) {
  auto fail = [&](const std::string& m) {
    if (why && why->empty()) *why = where + ": " + m;
    return false;
  };
  if (a.is_number() && b.is_number()) return std::abs(a.get<double>() - b.get<double>()) <= 1e-9 || fail(a.dump() + " vs " + b.dump());
  if (a.type() != b.type()) return fail(a.dump() + " vs " + b.dump());
  if (a.is_object()) {
    if (a.size() != b.size()) return fail("key sets differ: " + a.dump() + " vs " + b.dump());
    for (auto it = a.begin(); it != a.end(); ++it) {
      if (!b.contains(it.key())) return fail("missing key " + it.key());
      if (!sameJson(it.value(), b.at(it.key()), where + "." + it.key(), why)) return false;
    }
    return true;
  }
  if (a.is_array()) {
    if (a.size() != b.size()) return fail("array sizes differ");
    for (std::size_t i = 0; i < a.size(); ++i)
      if (!sameJson(a[i], b[i], where + "[" + std::to_string(i) + "]", why)) return false;
    return true;
  }
  return a == b || fail(a.dump() + " vs " + b.dump());
}

struct Case {
  const char* name;
  const char* presetFile;
  const char* mode;
  bool dropComp;
  const char* nam;
  const char* ir;
};
const Case kCases[] = {
    {"nocab", "nocab_preset.json", "nocab", false, "", ""},
    {"nocab_named", "nocab_preset.json", "nocab", false, "nocab-standard.nam", "nocab.ir.wav"},
    {"withcab_dropcomp", "withcab_preset.json", "withcab", true, "", ""},
    {"withcab_keepcomp", "withcab_preset.json", "withcab", false, "", ""},
    {"irmix_named", "irmix_preset.json", "nocab", false, "irmix-nocab-standard.nam", "irmix-nocab.ir.wav"},
};

}  // namespace

TEST_CASE("export notes: the preset JSON port equals the Python output (settings, hardware text, loader order, txt)", "[export-notes]") {
  for (const Case& c : kCases) {
    INFO(c.name);
    const json preset = readJson(kDir / c.presetFile);
    const json got = buildExportNotesFromJson(preset, c.mode, c.dropComp, c.nam, c.ir);
    const json want = readJson(kDir / (std::string(c.name) + ".notes.json"));
    std::string why;
    CHECK(sameJson(got, want, "notes", &why));
    CHECK(why == "");
    const std::string txt = formatNotesTxt(got, preset.at("name").get<std::string>());
    CHECK(txt == readText(kDir / (std::string(c.name) + ".export_notes.txt")));
    CHECK(exportNotesUsable(got));
  }
}

TEST_CASE("export notes: a parsed Preset gives the same notes as its JSON", "[export-notes]") {
  for (const Case& c : kCases) {
    INFO(c.name);
    const fs::path file = kDir / c.presetFile;
    const Preset p = parsePreset(readJson(file), file.parent_path());
    const json got = buildExportNotes(p, c.mode, c.dropComp, c.nam, c.ir);
    const json want = readJson(kDir / (std::string(c.name) + ".notes.json"));
    std::string why;
    CHECK(sameJson(got, want, "notes", &why));
    CHECK(why == "");
  }
}

TEST_CASE("export notes: what is listed follows the mode, the comp and DROP COMP", "[export-notes]") {
  const json nocab = readJson(kDir / "nocab_preset.json");
  auto stagesOf = [](const json& n) {
    std::string s;
    for (const auto& st : n.at("stages")) s += (s.empty() ? "" : ",") + st.at("stage").get<std::string>();
    return s;
  };
  CHECK(stagesOf(buildExportNotesFromJson(nocab, "nocab", true)) == "gate,cab,postEq,busComp");
  CHECK(stagesOf(buildExportNotesFromJson(nocab, "withcab", false)) == "gate");   // comp and cab are trained into a with-cab model
  CHECK(stagesOf(buildExportNotesFromJson(nocab, "withcab", true)) == "gate,busComp");

  json bare = nocab;
  bare["gate"]["enabled"] = false;
  bare["busComp"]["enabled"] = false;
  bare["cab"]["enabled"] = false;
  bare["postEq"] = json::array();
  const json none = buildExportNotesFromJson(bare, "nocab", false);
  CHECK(none.at("stages").empty());
  CHECK(none.at("message").get<std::string>().rfind("Nothing to add", 0) == 0);
  CHECK(none.at("loaderOrder") == "Loader order: NAM model");
  CHECK(formatNotesTxt(none).find("Nothing to add") != std::string::npos);
}

TEST_CASE("export notes: the output gain only moves the comp threshold of a no-cab export; defaults match notes.py", "[export-notes]") {
  json p = {{"gate", {{"enabled", true}}}, {"busComp", {{"enabled", true}}}, {"cab", {{"enabled", false}}}};
  const json n = buildExportNotesFromJson(p, "nocab", false);
  const json& gate = n.at("stages").at(0).at("settings");
  CHECK(gate.at("thresholdDb") == -55.0);
  CHECK(gate.at("closeThresholdDb") == -61.0);
  CHECK(gate.at("rangeDb") == -90.0);
  const json& comp = n.at("stages").at(1).at("settings");
  CHECK(comp.at("thresholdDb") == -12.0);
  CHECK(comp.at("ratio") == 2.0);
  CHECK(comp.at("releaseMs") == 100.0);
  CHECK(comp.at("thresholdDbFsOut") == -12.0);
  p["output"] = {{"gainDb", 3.0}};
  CHECK(buildExportNotesFromJson(p, "nocab", false).at("stages").at(1).at("settings").at("thresholdDbFsOut") == -9.0);
  CHECK(buildExportNotesFromJson(p, "withcab", true).at("stages").at(1).at("settings").at("thresholdDbFsOut") == -12.0);
}

TEST_CASE("export notes: foreign or damaged notes never throw and are not 'usable' unless version and shape match", "[export-notes]") {
  CHECK_FALSE(exportNotesUsable(json()));
  CHECK_FALSE(exportNotesUsable(json::array()));
  CHECK_FALSE(exportNotesUsable(json{{"version", 2}, {"stages", json::array()}, {"loaderOrder", "x"}}));
  CHECK_FALSE(exportNotesUsable(json{{"version", 1}, {"stages", 5}, {"loaderOrder", "x"}}));
  CHECK(exportNotesUsable(json{{"version", 1}, {"stages", json::array()}, {"loaderOrder", "x"}}));
  CHECK_NOTHROW(formatNotesTxt(json()));
  CHECK_NOTHROW(formatNotesTxt(json{{"mode", 3}, {"stages", json::array({1, "x", json{{"stage", 4}}})}, {"loaderOrder", 7}}));
  // A licence note replaces the disclaimer.
  const std::string t = formatNotesTxt(json{{"mode", "nocab"}, {"stages", json::array()}, {"loaderOrder", "Loader order: NAM model"}}, "My rig", "Own use only.");
  CHECK(t.find("Own use only.") != std::string::npos);
  CHECK(t.find("Derived from TONE3000") == std::string::npos);
  CHECK(t.rfind("Sawblade export notes - My rig (nocab export)\n", 0) == 0);
}

// ---- v0.6 Task C: model type (arch + size) settings, the A2 report, the Anagram profile ----------------------------------------

TEST_CASE("export settings: A2 Full by default; arch + size round trip; the pre-A2 size values migrate to A1", "[export][settings][a2]") {
  const ExportSettings def;
  CHECK(def.arch == "a2");
  CHECK(def.size == "full");
  CHECK(def.isDefault());

  // The five choices round trip; only the non-default ones are state worth saving (isDefault drives that).
  const std::pair<const char*, const char*> choices[] = {{"a2", "full"}, {"a2", "lite"}, {"a1", "feather"}, {"a1", "lite"}, {"a1", "standard"}};
  for (const auto& c : choices) {
    INFO(c.first << "/" << c.second);
    ExportSettings s;
    s.arch = c.first;
    s.size = c.second;
    const ExportSettings back = exportSettingsFromJson(exportSettingsToJson(s));
    CHECK(back == s);
    CHECK(exportSizeValid(c.first, c.second));
  }
  CHECK(exportSettingsToJson(ExportSettings{})["arch"] == "a2");

  // Migration: a saved object without `arch` is from before A2 and its size was an A1 size: the user keeps what they had.
  for (const char* old : {"feather", "lite", "standard"}) {
    const ExportSettings m = exportSettingsFromJson(json{{"mode", "withcab"}, {"size", old}, {"diSource", "builtin"}});
    CHECK(m.arch == "a1");
    CHECK(m.size == old);
    CHECK(m.mode == "withcab");
    CHECK(m.diSource == "builtin");
  }
  // An unknown old size: still pre-A2, so A1 and its default size.
  const ExportSettings huge = exportSettingsFromJson(json{{"size", "huge"}});
  CHECK(huge.arch == "a1");
  CHECK(huge.size == "standard");
  // Nothing saved: the new default.
  CHECK(exportSettingsFromJson(json::object()).isDefault());
  CHECK(exportSettingsFromJson(json(5)).isDefault());
  // A size that does not belong to the architecture falls back to that architecture's default; unknown arch keeps the default.
  CHECK(exportSettingsFromJson(json{{"arch", "a2"}, {"size", "standard"}}).size == "full");
  const ExportSettings a1full = exportSettingsFromJson(json{{"arch", "a1"}, {"size", "full"}});
  CHECK(a1full.arch == "a1");
  CHECK(a1full.size == "standard");
  const ExportSettings badArch = exportSettingsFromJson(json{{"arch", "a3"}, {"size", "lite"}});
  CHECK(badArch.arch == "a2");
  CHECK(badArch.size == "lite");
  CHECK(exportSettingsFromJson(json{{"arch", 3}, {"size", "lite"}}).arch == "a1");  // wrong-typed arch counts as absent: pre-A2
  CHECK(exportHistoryKey("a2", "full") == "a2.full");
  CHECK(defaultExportSize("a1") == "standard");
  CHECK(defaultExportSize("a2") == "full");
}

TEST_CASE("export wall-time history is kept per arch + size; the pre-A2 keys are A1's", "[export][settings][a2]") {
  const fs::path dir = fs::temp_directory_path() / ("sawblade_export_hist_" + std::to_string(std::random_device{}()));
  fs::create_directories(dir);
  const fs::path f = dir / "settings.xml";
  {
    // What an older build wrote: `exportWallSeconds.<size>` with no architecture.
    std::ofstream(f) << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n<PROPERTIES>\n  <VALUE name=\"exportWallSeconds.standard\" val=\"1500.0\"/>\n"
                        "  <VALUE name=\"exportWallSeconds.lite\" val=\"540.0\"/>\n</PROPERTIES>\n";
  }
  MatchSettings s(f);
  CHECK(s.exportWallSeconds("a1", "standard") == Catch::Approx(1500.0));
  CHECK(s.exportWallSeconds("a1", "lite") == Catch::Approx(540.0));
  CHECK(s.exportWallSeconds("a1", "feather") == 0.0);
  CHECK(s.exportWallSeconds("a2", "lite") == 0.0);  // the old A1 lite time is not A2 Lite's
  CHECK(s.exportWallSeconds("a2", "full") == 0.0);
  s.setExportWallSeconds("a2", "lite", 300.0);
  CHECK(s.exportWallSeconds("a2", "lite") == Catch::Approx(300.0));
  CHECK(s.exportWallSeconds("a1", "lite") == Catch::Approx(540.0));  // untouched
  s.setExportWallSeconds("a1", "lite", 600.0);                        // the new key wins over the legacy one
  CHECK(s.exportWallSeconds("a1", "lite") == Catch::Approx(600.0));
  std::error_code ec;
  fs::remove_all(dir, ec);
}

TEST_CASE("export report: A2 files block, the primary file, the validation of the chosen size, the Anagram profile", "[export][report][a2]") {
  const fs::path dir = fs::temp_directory_path() / ("sawblade_export_report_" + std::to_string(std::random_device{}()));
  fs::create_directories(dir);
  for (const char* n : {"riff-nocab-full.a2_full.nam", "riff-nocab-full.a2.nam", "riff-nocab-full.a2_lite.nam"}) std::ofstream(dir / n) << "{}";
  fs::copy_file(kDir / "report_a2_anagram.json", dir / "export_report.json");
  const ExportResult r = readExportResult(dir);
  REQUIRE(r.haveReport);
  CHECK(r.arch == "a2");
  CHECK(r.size == "full");
  CHECK(r.namFile == "riff-nocab-full.a2_full.nam");  // the primary file, whatever else is in the folder
  REQUIRE(r.otherFiles.size() == 2);
  CHECK(r.otherFiles[0].role == "container");
  CHECK(r.otherFiles[0].name == "riff-nocab-full.a2.nam");
  CHECK(r.otherFiles[1].role == "lite");
  CHECK(r.otherFiles[1].name == "riff-nocab-full.a2_lite.nam");
  CHECK(r.status == "MET");  // validation.full is the one `size` names; validation.lite (NOT MET) is not the verdict
  REQUIRE(r.heldOutEsr);
  CHECK(*r.heldOutEsr == Catch::Approx(0.0123));
  CHECK(exportBaseName(r.namFile) == "riff-nocab-full");
  CHECK(exportBaseName("x.a2.nam") == "x");
  CHECK(exportBaseName("x.a2_lite.nam") == "x");
  CHECK(exportBaseName("x-standard.nam") == "x-standard");

  const json notes = json::parse(r.exportNotesJson);
  CHECK(exportNotesUsable(notes));  // the generic profile is untouched
  const json profile = anagramProfileOf(notes);
  REQUIRE(profile.is_object());
  CHECK(anagramNotesFileName(profile) == "riff-nocab-full.anagram_notes.txt");
  const std::string txt = formatAnagramNotesTxt(profile, "My riff", "Own use only.");
  CHECK(txt.rfind("Sawblade export notes for the Anagram - My riff\n", 0) == 0);
  CHECK(txt.find("1. Gate [1 (first in the chain)]  (gate)\n") != std::string::npos);
  CHECK(txt.find("   threshold: -52\n") != std::string::npos);
  CHECK(txt.find("   hold ms: 20.5\n") != std::string::npos);
  CHECK(txt.find("   keyed on: guitar input\n") != std::string::npos);
  CHECK(txt.find("2. Neural Amp [2]  (model)\n") != std::string::npos);
  CHECK(txt.find("   bypass: off\n") != std::string::npos);
  CHECK(txt.find("3. IR [3]  (cab)\n") != std::string::npos);
  CHECK(txt.find("   Load without loudness normalisation.\n") != std::string::npos);
  CHECK(txt.find("Anagram chain: Gate -> Neural Amp -> IR\n") != std::string::npos);
  CHECK(txt.find("Own use only.") != std::string::npos);
  CHECK(txt.find("model: riff-nocab-full.a2_full.nam\n") != std::string::npos);
  // The generic text of the same notes is the v0.4M text, with no Anagram block names in it.
  CHECK(formatNotesTxt(notes).find("Neural Amp") == std::string::npos);
  std::error_code ec;
  fs::remove_all(dir, ec);
}

TEST_CASE("export report: A1 without deviceProfiles keeps the single-file contract", "[export][report][a2]") {
  const fs::path dir = fs::temp_directory_path() / ("sawblade_export_report1_" + std::to_string(std::random_device{}()));
  fs::create_directories(dir);
  std::ofstream(dir / "riff-nocab-standard.nam") << "{}";
  fs::copy_file(kDir / "report_a1_generic.json", dir / "export_report.json");
  const ExportResult r = readExportResult(dir);
  CHECK(r.arch == "a1");
  CHECK(r.namFile == "riff-nocab-standard.nam");
  CHECK(r.otherFiles.empty());
  CHECK(r.status == "MET");
  const json notes = json::parse(r.exportNotesJson);
  CHECK(exportNotesUsable(notes));
  CHECK(anagramProfileOf(notes).is_null());
  // A report from before v0.6 has no arch / size / files at all: the .nam is found by looking, as before.
  json old = json::parse(readText(dir / "export_report.json"));
  for (const char* k : {"arch", "size", "files"}) old.erase(k);
  std::ofstream(dir / "export_report.json") << old.dump();
  const ExportResult o = readExportResult(dir);
  CHECK(o.arch.empty());
  CHECK(o.namFile == "riff-nocab-standard.nam");
  CHECK(o.otherFiles.empty());
  CHECK(o.status == "MET");

  // Tolerance: a profile of the wrong type, or odd members, never throws and never produces a profile / stray text.
  CHECK(anagramProfileOf(json{{"deviceProfiles", 3}}).is_null());
  CHECK(anagramProfileOf(json{{"deviceProfiles", {{"anagram", "x"}}}}).is_null());
  CHECK(anagramProfileOf(json(7)).is_null());
  const std::string odd = formatAnagramNotesTxt(json{{"blocks", json::array({json{{"block", "Compressor"}, {"settings", json::array({json{{"key", "ratio"}, {"value", 2.5}}, "free text"})}}, 5})}});
  CHECK(odd.find("1. Compressor\n   ratio: 2.5\n   free text\n") != std::string::npos);
  CHECK(odd.find("2. (block)\n") != std::string::npos);
  CHECK(formatAnagramNotesTxt(json::object()).find("Nothing to add") != std::string::npos);
  std::error_code ec;
  fs::remove_all(dir, ec);
}
