// Export notes (v0.4 Task E): the C++ port of v0.4M's notes.py must reproduce the Python output. The fixtures in
// tests/fixtures/export_notes/ were generated by running that Python (generate.py there has the command).
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <string>

#include <catch2/catch_test_macros.hpp>
#include <nlohmann/json.hpp>

#include "ExportNotes.h"
#include "sawblade/preset.h"

using nlohmann::json;
using namespace sawblade;
using namespace sawblade::plugin;
namespace fs = std::filesystem;

namespace {

const fs::path kDir = fs::path(SAWBLADE_EXPORT_NOTES_DIR);

std::string readText(const fs::path& p) {
  std::ifstream f(p, std::ios::binary);
  REQUIRE(f.good());
  return std::string((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
}
json readJson(const fs::path& p) { return json::parse(readText(p)); }

// Numbers within 1e-9 (an int and a float of the same value are equal), strings and everything else exact.
bool sameJson(const json& a, const json& b, const std::string& where, std::string* why) {
  auto fail = [&](const std::string& m) {
    if (why && why->empty()) *why = where + ": " + m;
    return false;
  };
  if (a.is_number() && b.is_number()) return std::abs(a.get<double>() - b.get<double>()) <= 1e-9 || fail(a.dump() + " vs " + b.dump());
  if (a.type() != b.type()) return fail(a.dump() + " vs " + b.dump());
  if (a.is_object()) {
    if (a.size() != b.size()) return fail("key sets differ: " + a.dump() + " vs " + b.dump());
    for (auto it = a.begin(); it != a.end(); ++it) {
      if (!b.contains(it.key())) return fail("missing key " + it.key());
      if (!sameJson(it.value(), b.at(it.key()), where + "." + it.key(), why)) return false;
    }
    return true;
  }
  if (a.is_array()) {
    if (a.size() != b.size()) return fail("array sizes differ");
    for (std::size_t i = 0; i < a.size(); ++i)
      if (!sameJson(a[i], b[i], where + "[" + std::to_string(i) + "]", why)) return false;
    return true;
  }
  return a == b || fail(a.dump() + " vs " + b.dump());
}

struct Case {
  const char* name;
  const char* presetFile;
  const char* mode;
  bool dropComp;
  const char* nam;
  const char* ir;
};
const Case kCases[] = {
    {"nocab", "nocab_preset.json", "nocab", false, "", ""},
    {"nocab_named", "nocab_preset.json", "nocab", false, "nocab-standard.nam", "nocab.ir.wav"},
    {"withcab_dropcomp", "withcab_preset.json", "withcab", true, "", ""},
    {"withcab_keepcomp", "withcab_preset.json", "withcab", false, "", ""},
    {"irmix_named", "irmix_preset.json", "nocab", false, "irmix-nocab-standard.nam", "irmix-nocab.ir.wav"},
};

}  // namespace

TEST_CASE("export notes: the preset JSON port equals the Python output (settings, hardware text, loader order, txt)", "[export-notes]") {
  for (const Case& c : kCases) {
    INFO(c.name);
    const json preset = readJson(kDir / c.presetFile);
    const json got = buildExportNotesFromJson(preset, c.mode, c.dropComp, c.nam, c.ir);
    const json want = readJson(kDir / (std::string(c.name) + ".notes.json"));
    std::string why;
    CHECK(sameJson(got, want, "notes", &why));
    CHECK(why == "");
    const std::string txt = formatNotesTxt(got, preset.at("name").get<std::string>());
    CHECK(txt == readText(kDir / (std::string(c.name) + ".export_notes.txt")));
    CHECK(exportNotesUsable(got));
  }
}

TEST_CASE("export notes: a parsed Preset gives the same notes as its JSON", "[export-notes]") {
  for (const Case& c : kCases) {
    INFO(c.name);
    const fs::path file = kDir / c.presetFile;
    const Preset p = parsePreset(readJson(file), file.parent_path());
    const json got = buildExportNotes(p, c.mode, c.dropComp, c.nam, c.ir);
    const json want = readJson(kDir / (std::string(c.name) + ".notes.json"));
    std::string why;
    CHECK(sameJson(got, want, "notes", &why));
    CHECK(why == "");
  }
}

TEST_CASE("export notes: what is listed follows the mode, the comp and DROP COMP", "[export-notes]") {
  const json nocab = readJson(kDir / "nocab_preset.json");
  auto stagesOf = [](const json& n) {
    std::string s;
    for (const auto& st : n.at("stages")) s += (s.empty() ? "" : ",") + st.at("stage").get<std::string>();
    return s;
  };
  CHECK(stagesOf(buildExportNotesFromJson(nocab, "nocab", true)) == "gate,cab,postEq,busComp");
  CHECK(stagesOf(buildExportNotesFromJson(nocab, "withcab", false)) == "gate");   // comp and cab are trained into a with-cab model
  CHECK(stagesOf(buildExportNotesFromJson(nocab, "withcab", true)) == "gate,busComp");

  json bare = nocab;
  bare["gate"]["enabled"] = false;
  bare["busComp"]["enabled"] = false;
  bare["cab"]["enabled"] = false;
  bare["postEq"] = json::array();
  const json none = buildExportNotesFromJson(bare, "nocab", false);
  CHECK(none.at("stages").empty());
  CHECK(none.at("message").get<std::string>().rfind("Nothing to add", 0) == 0);
  CHECK(none.at("loaderOrder") == "Loader order: NAM model");
  CHECK(formatNotesTxt(none).find("Nothing to add") != std::string::npos);
}

TEST_CASE("export notes: the output gain only moves the comp threshold of a no-cab export; defaults match notes.py", "[export-notes]") {
  json p = {{"gate", {{"enabled", true}}}, {"busComp", {{"enabled", true}}}, {"cab", {{"enabled", false}}}};
  const json n = buildExportNotesFromJson(p, "nocab", false);
  const json& gate = n.at("stages").at(0).at("settings");
  CHECK(gate.at("thresholdDb") == -55.0);
  CHECK(gate.at("closeThresholdDb") == -61.0);
  CHECK(gate.at("rangeDb") == -90.0);
  const json& comp = n.at("stages").at(1).at("settings");
  CHECK(comp.at("thresholdDb") == -12.0);
  CHECK(comp.at("ratio") == 2.0);
  CHECK(comp.at("releaseMs") == 100.0);
  CHECK(comp.at("thresholdDbFsOut") == -12.0);
  p["output"] = {{"gainDb", 3.0}};
  CHECK(buildExportNotesFromJson(p, "nocab", false).at("stages").at(1).at("settings").at("thresholdDbFsOut") == -9.0);
  CHECK(buildExportNotesFromJson(p, "withcab", true).at("stages").at(1).at("settings").at("thresholdDbFsOut") == -12.0);
}

TEST_CASE("export notes: foreign or damaged notes never throw and are not 'usable' unless version and shape match", "[export-notes]") {
  CHECK_FALSE(exportNotesUsable(json()));
  CHECK_FALSE(exportNotesUsable(json::array()));
  CHECK_FALSE(exportNotesUsable(json{{"version", 2}, {"stages", json::array()}, {"loaderOrder", "x"}}));
  CHECK_FALSE(exportNotesUsable(json{{"version", 1}, {"stages", 5}, {"loaderOrder", "x"}}));
  CHECK(exportNotesUsable(json{{"version", 1}, {"stages", json::array()}, {"loaderOrder", "x"}}));
  CHECK_NOTHROW(formatNotesTxt(json()));
  CHECK_NOTHROW(formatNotesTxt(json{{"mode", 3}, {"stages", json::array({1, "x", json{{"stage", 4}}})}, {"loaderOrder", 7}}));
  // A licence note replaces the disclaimer.
  const std::string t = formatNotesTxt(json{{"mode", "nocab"}, {"stages", json::array()}, {"loaderOrder", "Loader order: NAM model"}}, "My rig", "Own use only.");
  CHECK(t.find("Own use only.") != std::string::npos);
  CHECK(t.find("Derived from TONE3000") == std::string::npos);
  CHECK(t.rfind("Sawblade export notes - My rig (nocab export)\n", 0) == 0);
}
