# ctest helper: plugin/assets/ must stay under 25 MB and contain every file the exporter lists.
# Usage: cmake -DASSETS_DIR=... -DEXPORTER=... -DPYTHON=... -P check_assets.cmake
execute_process(COMMAND ${PYTHON} ${EXPORTER} --list OUTPUT_VARIABLE _list RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
  message(FATAL_ERROR "export_ui_assets.py --list failed (${_rc})")
endif()
string(REGEX REPLACE "[\r\n]+" ";" _files "${_list}")
set(_missing "")
set(_n 0)
foreach(_f ${_files})
  if(_f STREQUAL "")
    continue()
  endif()
  math(EXPR _n "${_n} + 1")
  if(NOT EXISTS "${ASSETS_DIR}/${_f}")
    list(APPEND _missing ${_f})
  endif()
endforeach()
if(_n EQUAL 0)
  message(FATAL_ERROR "exporter listed no files")
endif()
if(_missing)
  message(FATAL_ERROR "missing assets: ${_missing}")
endif()
file(GLOB_RECURSE _all "${ASSETS_DIR}/*")
set(_total 0)
foreach(_f ${_all})
  file(SIZE "${_f}" _s)
  math(EXPR _total "${_total} + ${_s}")
endforeach()
math(EXPR _limit "25 * 1000 * 1000")
message(STATUS "assets: ${_n} files listed, total ${_total} bytes (limit ${_limit})")
if(_total GREATER_EQUAL _limit)
  message(FATAL_ERROR "plugin/assets is ${_total} bytes, over the 25 MB budget")
endif()
