"""calibration_report.md and PNGs."""
from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

from ..tonecheck.rules import evaluate_rules, parse_expr  # noqa: E402
from .measure import Measured  # noqa: E402
from .propose import measured_diff  # noqa: E402

METHOD_COLOUR = {"stems": "#1565c0", "sections": "#e65100", "side": "#6a1b9a"}
REF_STYLE = {"original": "-", "cover": "--"}


def _style(key: str) -> tuple[str, str]:
    ref, _, method = key.partition("/")
    return METHOD_COLOUR.get(method.split()[0], "#555555"), REF_STYLE.get(ref, ":")


def ltas_png(path: Path, results: dict[str, Measured], groups_def: dict, extra: dict[str, Measured] | None = None) -> None:
    fig, ax = plt.subplots(figsize=(11, 5.4))
    for name, bands in groups_def.items():
        ax.axvspan(bands[0] * 2 ** (-1 / 6), bands[-1] * 2 ** (1 / 6), color="#9e9e9e", alpha=0.10)
        ax.text(np.sqrt(bands[0] * bands[-1]), 20, name, ha="center", fontsize=8)
    for key, m in results.items():
        c, ls = _style(key)
        ax.semilogx(m.centres, m.rel_db, ls, color=c, lw=2, marker="o", ms=4, label=key)
    for key, m in (extra or {}).items():
        ax.semilogx(m.centres, m.rel_db, ":", color="#2e7d32", lw=2, marker="s", ms=4, label=key)
    ax.set_xlim(22, 15000)
    ax.set_ylim(-45, 22)
    ax.set_xlabel("1/3-octave centre (Hz)")
    ax.set_ylabel("dB re 1 kHz band")
    ax.set_title("Guitar LTAS: original (solid) vs cover (dashed); colour = isolation method")
    ax.grid(True, which="both", alpha=0.3)
    ax.legend(loc="lower left", fontsize=8)
    fig.tight_layout()
    fig.savefig(path, dpi=110)
    plt.close(fig)


def thresholds_png(path: Path, table: list[dict], results: dict[str, Measured], targets: dict) -> None:
    """Per rule: measured (lhs - rhs) dB for every ref x method, the current and the proposed threshold."""
    rules = targets["rules"]
    fig, ax = plt.subplots(figsize=(11, 0.62 * len(rules) + 1.8))
    for i, (row, rule) in enumerate(zip(table, rules)):
        y = len(rules) - 1 - i
        e_cur, e_new = parse_expr(row["currentExpr"]), parse_expr(row["proposedExpr"])
        ax.plot([e_cur.offset], [y + 0.18], marker="|", ms=16, mew=3, color="#444444",
                label="current threshold" if i == 0 else None, ls="none")
        ax.plot([e_new.offset], [y + 0.18], marker="D", ms=7, color="#c62828" if row["decision"] == "contradicted" else "#2e7d32",
                label="proposed threshold" if i == 0 else None, ls="none")
        ax.annotate("<= allowed" if e_cur.op == "<=" else ">= allowed", (e_cur.offset, y + 0.18), xytext=(0, 9),
                    textcoords="offset points", fontsize=6, ha="center", color="#666666")
        for k, (key, m) in enumerate(results.items()):
            c, _ = _style(key)
            mk = "o" if key.startswith("original") else "s"
            ax.plot([measured_diff(rule, m.groups)], [y - 0.1 - 0.12 * k], marker=mk, ms=6, color=c,
                    mfc=c if key.startswith("original") else "none", ls="none", label=key if i == 0 else None)
    ax.set_yticks(range(len(rules)))
    ax.set_yticklabels([f"{r['id']}\n{r['expr']}" for r in reversed(rules)], fontsize=7)
    ax.set_xlabel("measured lhs - rhs (dB); thresholds are the rule's offset")
    ax.axvline(0, color="#999999", lw=0.6)
    ax.grid(True, axis="x", alpha=0.3)
    ax.set_title("Rules: measured values vs current / proposed thresholds (red diamond = contradicted, not changed)")
    ax.legend(loc="lower right", fontsize=7, ncol=2)
    fig.tight_layout()
    fig.savefig(path, dpi=110)
    plt.close(fig)


def _f(v, fmt):
    return "n/a" if v is None else format(v, fmt)


def markdown(*, inputs: dict, availability: dict, results: dict[str, Measured], targets: dict, proposed: dict,
             table: list[dict], contradicted: list[dict], basis: str, scores: dict[str, dict], notes: list[str],
             selection_notes: dict[str, str], pngs: list[str]) -> str:
    L: list[str] = ["# Calibration report", "", "Generated by `sawblade-calibrate`. Deterministic (no random processes; "
                    "demucs seed 0, shifts=0 when it runs). Nothing here modifies `docs/tone_targets.json`.", ""]
    L += ["## Inputs and method availability", ""]
    for k, v in inputs.items():
        L.append(f"- {k}: `{v}`")
    L.append("")
    for k, v in availability.items():
        L.append(f"- {k}: {v}")
    L += ["", f"Proposal basis (original): **{basis}**", ""]
    for n in notes:
        L.append(f"- {n}")
    L += ["", "## Selection details", ""]
    for k, v in selection_notes.items():
        L.append(f"- **{k}**: {v}")
    keys = list(results)
    gnames = list(targets["analysis"]["bandGroups"])
    L += ["", "## Group levels (dB re 1 kHz band)", "", "| signal | " + " | ".join(gnames) + " | selected | Welch segs |",
          "|---|" + "---|" * (len(gnames) + 2)]
    for k in keys:
        m = results[k]
        L.append(f"| {k} | " + " | ".join(f"{m.groups[g]:+.1f}" for g in gnames) +
                 f" | {m.selected_seconds:.0f} s ({100 * m.selected_fraction:.0f} %) | {m.n_segments} |")
    spread = {k: results[k].chunk_spread_db for k in keys if results[k].chunk_spread_db}
    if spread:
        L += ["", "Std across 10 s chunks of the selected material (reliability; small = one consistent tone):", ""]
        for k, s in spread.items():
            L.append(f"- {k}: " + ", ".join(f"{g} {v:.1f}" for g, v in s.items()) + " dB")
    L += ["", "## Rules: measured value (lhs - rhs, dB) per signal", "",
          "Current rule: status under the **current** thresholds (P pass / M marginal / F fail).", "",
          "| rule | current | tol | " + " | ".join(keys) + " |", "|---|---|---|" + "---|" * len(keys)]
    for i, rule in enumerate(targets["rules"]):
        cells = []
        for k in keys:
            r = evaluate_rules(results[k].groups, [rule])[0]
            cells.append(f"{measured_diff(rule, results[k].groups):+.1f} {r['status'][0].upper()}")
        L.append(f"| {rule['id']} | `{rule['expr']}` | {rule.get('toleranceDb', 0):g} | " + " | ".join(cells) + " |")
    L += ["", "## Metrics", "", "| signal | buzz | lowTightnessMs (n meas/onsets) | lowDecayDbPerMs (n) | crest dB |", "|---|---|---|---|---|"]
    for k in keys:
        m = results[k].metrics
        L.append(f"| {k} | {m['buzz']['value']:.3f} | {_f(m['lowTightnessMs']['valueMs'], '.0f')} "
                 f"({m['lowTightnessMs']['nMeasured']}/{m['lowTightnessMs']['nOnsets']}) | "
                 f"{_f(m['lowDecayDbPerMs']['value'], '.3f')} ({m['lowDecayDbPerMs']['nMeasured']}) | "
                 f"{m['crestFactorDb']['value']:.1f} |")
    L += ["", "Caveat: for the section methods the 80-160 Hz envelope is taken from the full mix, which still holds "
          "bass and kick under the kept frames; read the low-end metrics of section rows as upper bounds on "
          "looseness. Onsets are detected on the analysed signal itself (the cover has DIs, but the original "
          "has none, so both use the same self-onset scheme).", ""]
    L += ["## Proposed thresholds vs current", "", "| rule | current | proposed | change dB | measured diff | current status on basis | decision |",
          "|---|---|---|---|---|---|---|"]
    for r in table:
        L.append(f"| {r['id']} | `{r['currentExpr']}` | `{r['proposedExpr']}` | {r['thresholdChangeDb']:+.1f} | "
                 f"{r['measuredDiffDb']:+.1f} | {r['currentStatusOnBasis']} | {r['decision']} |")
    L += ["", "## Rules the data contradicts (left unchanged in the proposal)", ""]
    if not contradicted:
        L.append("None: the original's guitars satisfy every current rule within tolerance.")
    for c in contradicted:
        L.append(f"- **{c['id']}** (`{c['currentExpr']}`; why: {c['why']}): {c['evidence']}. "
                 f"If accepted: `{c['proposedExpr']}`. Other methods: {c['otherMethods'] or 'n/a'}")
    if scores:
        L += ["", "## Smoke render scored under both target sets", ""]
        for name, s in scores.items():
            L += [f"### {name}", "", "| rule | value | current thr | current margin | status | proposed thr | proposed margin | status |",
                  "|---|---|---|---|---|---|---|---|"]
            for a, b in zip(s["current"], s["proposed"]):
                L.append(f"| {a['id']} | {a['value']:+.1f} | {a['threshold']:+.1f} | {a['margin']:+.1f} | {a['status']} | "
                         f"{b['threshold']:+.1f} | {b['margin']:+.1f} | {b['status']} |")
            L.append("")
    L += ["## Figures", ""] + [f"![{p}]({p})" for p in pngs] + [""]
    return "\n".join(L)
